#!/usr/bin/python
"""travel back in time in a git repository, by just entering
 * a number of commits you want to go back (or a hash).
 * When you want get back to 'now' including the local changes
 * git-timetravel now takes you back into the future.
 * Repository and issue-tracker: https://github.com/docopt/docopt
 * Licensed under terms of MIT license (see LICENSE-MIT)
 * Copyright (c) 2013 Vladimir Keleshev, vladimir@keleshev.com
 * Copyright (c) 2014 Tobias Glaesser

"""
import os
import sys
import re
import datetime
import subprocess
import tempfile

from docopt import docopt

__all__ = ['git-timetravel']
__version__ = '0.1.0'

doc ='''
Usage:
  git-timetravel back [NUM]
  git-timetravel forward [NUM]
  git-timetravel anchor
  git-timetravel <commit>
  git-timetravel --help
  git-timetravel --version

Travel in time through your git repository.
Then go back to the future with git-timetravel anchor,
not losing any local changes.

When you first go back using <commit> or back [num]
git-timetravel remembers where you were as the anchor.
If you then use the anchor command at any time you'll be taken
back to that anchor.

This tool is intended for trying earlier revisions of code,
i.e. to test for regressions.

arguments:
  <commit>                     go back to specific commit
                               will refuse going forward

commands:
  back [NUM]                   go back by [NUM] commits
                               (default is 1)
  forward [NUM]                go forward by [NUM] commits
                               (default is 1)
  anchor                       get back to the anchor including
                               any local changes

Options:
  -h, --help                   show this help message and exit
  -v, --version                display version information

'''

opt = docopt(doc,None,True,__version__)

print opt

def set_anchor():
    ''
    #only set anchor if none is set

def get_anchor():
    ''
    #if no anchor is set return None

def get_num(n):
    if n:
        return n
    return "1"

def travel_to_anchor():
    #travel to anchor
    #then remove the anchor
    #then apply stashed changes
    ''

def stash_changes():
    #find out if there are local changes
    #if so create stash

if opt['anchor']:
    ''
    #back to the future
    exit(0)

elif opt['back']:
    #git checkout HEAD~1
    print "hello"
    anchor = get_anchor()
    num = get_num(opt['NUM'])
    if not anchor:
        anchor = set_anchor()
    subprocess.call('git checkout./'+opt['--output'],shell=True)

elif opt['forward']:
    print "forward"

elif opt['<commit>']:
    print "commit"



